#!/bin/bash

echo
echo "----------------------------------------------------------------------------"
echo "----------------------------- PASCAL-TDS 2017 ------------------------------"
echo "---------------------- Boselli - Etcharren - Gonzalez ----------------------"
echo "---------------------------- Compiladores (3306) ---------------------------"
echo "----------------------------------------------------------------------------"
echo 
echo "----------------------------------------------------------------------------"

if [ "$1" == "-m" ]; then
	echo "------------------------------- MacOS Edition ------------------------------"
else
	echo "------------------------------- Linux Edition ------------------------------"
fi

echo "----------------------------------------------------------------------------"  
echo
echo "----------------------------------------------------------------------------"
echo "----------------------------- Execute all tests ----------------------------"
echo "----------------------------------------------------------------------------"
echo 
echo "----------------------------------------------------------------------------"
echo "------------------------ DIRECTORIO PRUEBAS/SUCCESS ------------------------"
echo "----------------------------------------------------------------------------"
echo

for archivoActual in $(ls Pruebas/Success);do
	echo "----------------------------------------------------------------------------"
	echo "Running "$archivoActual" ..."

	if [ "$1" == "-m" ]; then
		./pascaltds 0 1 < "./Pruebas/Success/"$archivoActual
	else
		./pascaltds 0 0 < "./Pruebas/Success/"$archivoActual
	fi

	gcc assemblyCode.s -o assemblyCode
	./assemblyCode
	echo "Return: "$?
	echo
done

echo
echo "----------------------------------------------------------------------------"
echo "------------------------- DIRECTORIO PRUEBAS/FAIL --------------------------"
echo "----------------------------------------------------------------------------"
echo

for archivoActual in $(ls Pruebas/Fail);do
	echo "----------------------------------------------------------------------------"
	echo "Running "$archivoActual" ..."

	if [ "$1" == "-m" ]; then
		./pascaltds 0 1 < "./Pruebas/Fail/"$archivoActual
	else
		./pascaltds 0 0 < "./Pruebas/Fail/"$archivoActual
	fi
	echo
done

echo
echo "----------------------------------------------------------------------------"
echo "------------------ DIRECTORIO PRUEBAS-SEMANTICAS/SUCCESS -------------------"
echo "----------------------------------------------------------------------------"
echo

for archivoActual in $(ls Pruebas-Semanticas/Success);do
	echo "----------------------------------------------------------------------------"
	echo "Running "$archivoActual" ..."

	if [ "$1" == "-m" ]; then
		./pascaltds 0 1 < "./Pruebas-Semanticas/Success/"$archivoActual
	else
		./pascaltds 0 0 < "./Pruebas-Semanticas/Success/"$archivoActual
	fi
	
	gcc assemblyCode.s -o assemblyCode
	./assemblyCode
	echo "Return: "$?
	echo
done

echo
echo "----------------------------------------------------------------------------"
echo "-------------------- DIRECTORIO PRUEBAS-SEMANTICAS/FAIL --------------------"
echo "----------------------------------------------------------------------------"
echo

for archivoActual in $(ls Pruebas-Semanticas/Fail);do
	echo "----------------------------------------------------------------------------"
	echo "Running "$archivoActual" ..."

	if [ "$1" == "-m" ]; then
		./pascaltds 0 1 < "./Pruebas-Semanticas/Fail/"$archivoActual
	else
		./pascaltds 0 0 < "./Pruebas-Semanticas/Fail/"$archivoActual
	fi
	echo
done

echo
echo "----------------------------------------------------------------------------"
echo "------------------- DIRECTORIO PRUEBAS-CODIGO-INTERMEDIO -------------------"
echo "----------------------------------------------------------------------------"
echo
echo

for archivoActual in $(ls Pruebas-Codigo-Intermedio/Success);do
	echo "----------------------------------------------------------------------------"
	echo "Running "$archivoActual" ..."

	if [ "$1" == "-m" ]; then
		./pascaltds 0 1 < "./Pruebas-Codigo-Intermedio/Success/"$archivoActual
	else
		./pascaltds 0 0 < "./Pruebas-Codigo-Intermedio/Success/"$archivoActual
	fi

	gcc assemblyCode.s -o assemblyCode
	./assemblyCode
	echo "Return: "$?
	echo
done

echo
echo "----------------------------------------------------------------------------"
echo "--------------------- DIRECTORIO PRUEBAS-CODIGO-OBJETO ---------------------"
echo "----------------------------------------------------------------------------"
echo
echo

for archivoActual in $(ls Pruebas-Codigo-Objeto);do
	echo "----------------------------------------------------------------------------"
	echo "Running "$archivoActual" ..."

	if [ "$1" == "-m" ]; then
		./pascaltds 0 1 < "./Pruebas-Codigo-Objeto/"$archivoActual
	else
		./pascaltds 0 0 < "./Pruebas-Codigo-Objeto/"$archivoActual
	fi

	gcc assemblyCode.s -o assemblyCode
	./assemblyCode
	echo "Return: "$?
	echo
done

echo
echo "----------------------------------------------------------------------------"
echo "-------------------------------- Fin Pruebas -------------------------------"
echo "----------------------------------------------------------------------------"
echo

exit
