#!/bin/bash

echo
echo "----------------------------------------------------------------------------"
echo "----------------------------- PASCAL-TDS 2017 ------------------------------"
echo "---------------------- Boselli - Etcharren - Gonzalez ----------------------"
echo "---------------------------- Compiladores (3306) ---------------------------"
echo "----------------------------------------------------------------------------"
echo 
echo "----------------------------------------------------------------------------"
echo "----------------------------- Execute all tests ----------------------------"
echo "----------------------------------------------------------------------------"
echo 

echo "----------------------------------------------------------------------------"
echo "------------------------ DIRECTORIO PRUEBAS/SUCCESS ------------------------"
echo "----------------------------------------------------------------------------"
echo

for archivoActual in $(ls Pruebas/Success);do
	echo "----------------------------------------------------------------------------"
	echo "Running "$archivoActual" ..."
	./pascaltds 1 < "./Pruebas/Success/"$archivoActual
	echo
done

echo
echo "----------------------------------------------------------------------------"
echo "------------------------- DIRECTORIO PRUEBAS/FAIL --------------------------"
echo "----------------------------------------------------------------------------"
echo

for archivoActual in $(ls Pruebas/Fail);do
	echo "----------------------------------------------------------------------------"
	echo "Running "$archivoActual" ..."
	./pascaltds 1 < "./Pruebas/Fail/"$archivoActual
	echo
done

echo
echo "----------------------------------------------------------------------------"
echo "------------------ DIRECTORIO PRUEBAS-SEMANTICAS/SUCCESS -------------------"
echo "----------------------------------------------------------------------------"
echo

for archivoActual in $(ls Pruebas-Semanticas/Success);do
	echo "----------------------------------------------------------------------------"
	echo "Running "$archivoActual" ..."
	./pascaltds 1 < "./Pruebas-Semanticas/Success/"$archivoActual
	echo
done

echo
echo "----------------------------------------------------------------------------"
echo "-------------------- DIRECTORIO PRUEBAS-SEMANTICAS/FAIL --------------------"
echo "----------------------------------------------------------------------------"
echo

for archivoActual in $(ls Pruebas-Semanticas/Fail);do
	echo "----------------------------------------------------------------------------"
	echo "Running "$archivoActual" ..."
	./pascaltds 1 < "./Pruebas-Semanticas/Fail/"$archivoActual
	echo
done

echo
echo "----------------------------------------------------------------------------"
echo "------------------- DIRECTORIO PRUEBAS-CODIGO-INTERMEDIO -------------------"
echo "----------------------------------------------------------------------------"
echo
echo

for archivoActual in $(ls Pruebas-Codigo-Intermedio/Success);do
	echo "----------------------------------------------------------------------------"
	echo "Running "$archivoActual" ..."
	./pascaltds 1 < "./Pruebas-Codigo-Intermedio/Success/"$archivoActual
	echo
done

echo
echo "----------------------------------------------------------------------------"
echo "-------------------------------- Fin Pruebas -------------------------------"
echo "----------------------------------------------------------------------------"
echo

exit
