#!/bin/bash

echo
echo "----------------------------------------------------------------------------"
echo "----------------------------- PASCAL-TDS 2017 ------------------------------"
echo "---------------------- Boselli - Etcharren - Gonzalez ----------------------"
echo "---------------------------- Compiladores (3306) ---------------------------"
echo "----------------------------------------------------------------------------"
echo
echo "----------------------------------------------------------------------------"
echo "------------------------------- MacOS Edition ------------------------------"
echo "----------------------------------------------------------------------------"  
echo
echo "----------------------------------------------------------------------------"
echo "------------------------------ Compiling File ------------------------------"
echo "----------------------------------------------------------------------------" 
echo

# Compiler Instructions:
#   ./ptds-compiler [flag] (target) /path/to/file -opt
#   
#   Without flag, is normal execution.
#   The flag could be:
#       -o      : Renames the excecutable. It needs a target that will be the new name.
#       -target : Proceeds until target. It needs a target that could be:
#                   * scan      : proceeds until flex scan.
#                   * parse     : proceeds until yacc parse.
#                   * codinter  : proceeds until intermediate code generation.
#                   * assembler : proceeds until assembler code generation.
#       -debug  : Debug execution.
#       -ic     : Shows intermediate code.
#       -ac     : Shows assembler code.


# pascaltds flags
#   0 : Normal (Executes all, shows nothing)
#   1 : Debug (Executes all, shows debug messages)
#   2 : Intermediate code (Executes all, show intermediate code)
#   3 : Assembly code (Executes all, shows assembly code)
#   4 : Taget scan (Executes until flex scan, shows debug messages)
#   5 : Target parse (Execures until yacc parse, shows debug messages)
#   6 : Target codinter (Executes until intermediate code generation, shows generated code)
#   7 : Target assembly (Executes until assembly code generation, shows generated code)

#echo "1) $1"
#echo "2) $2"
#echo "3) $3"

# Option
if [ "$1" != "" ]; then
    case $1 in

        # Rename executable
        -o)
            echo "-o"
            if [ "$2" != "" ]; then
                if [ "$3" != "" ]; then
                    if [ "$4" != "" ]; then
                        if [ "$4" == "-op" ]; then
                            ./pascaltds 0 1 1 < "./"$3
                        else
                            echo "Error: Unknown flag '"$4"'."  
                            exit
                        fi
                    else
                        ./pascaltds 0 1 0 < "./"$3
                    fi
                    gcc assemblyCode.s -o $2 
                else
                    echo "Error: Empty file parameter."
                    exit
                fi
            else
                echo "Error: Empty output file name."
            fi
        ;;

        # Proceeds until target (scan, parse, codinter, assembly)
        -target)
            if [ "$2" != "" ]; then
                # Switch between target flags
                case $2 in
                    scan)
                        echo "-target scan"
                        echo
                        # Get file name
                        if [ "$3" != "" ]; then
                            if [ "$4" != "" ]; then
                                if [ "$4" == "-op" ]; then
                                    ./pascaltds 4 1 1 < "./"$3
                                else
                                    echo "Error: Unknown flag '"$4"'."  
                                    exit 
                                fi
                            else
                                ./pascaltds 4 1 0 < "./"$3
                            fi
                        else
                            echo "Error: Empty file parameter."
                            exit
                        fi
                    ;;

                    parse)
                        echo "-target parse"
                        echo
                        # Get file name
                        if [ "$3" != "" ]; then
                            if [ "$4" != "" ]; then
                                if [ "$4" == "-op" ]; then
                                    ./pascaltds 5 1 1 < "./"$3
                                else
                                    echo "Error: Unknown flag '"$4"'."  
                                    exit 
                                fi
                            else
                                ./pascaltds 5 1 0 < "./"$3
                            fi
                        else
                            echo "Error: Empty file parameter."
                            exit
                        fi
                    ;;

                    codinter)
                        echo "-target codinter"
                        echo
                        # Get file name
                        if [ "$3" != "" ]; then
                            if [ "$4" != "" ]; then
                                if [ "$4" == "-op" ]; then
                                    ./pascaltds 6 1 1 < "./"$3
                                else
                                    echo "Error: Unknown flag'"$4"'."  
                                    exit 
                                fi
                            else
                                ./pascaltds 6 1 0 < "./"$3
                            fi
                        else
                            echo "Error: Empty file parameter."
                            exit
                        fi
                    ;;

                    assembly)
                        echo "-target assembly"
                        echo
                        # Get file name
                        if [ "$3" != "" ]; then
                            if [ "$4" != "" ]; then
                                if [ "$4" == "-op" ]; then
                                    ./pascaltds 7 1 1 < "./"$3
                                else
                                    echo "Error: Unknown flag '"$4"'."  
                                    exit 
                                fi
                            else
                                ./pascaltds 7 1 0 < "./"$3
                            fi
                        else
                            echo "Error: Empty file parameter."
                            exit
                        fi
                    ;;

                    *)
                        echo "Error: '"$2"' is not a target flag. [ scan | parse | codinter | assembly ]"
                        exit
                    ;;
                esac
            else
                echo "Error: Missing target flag. [ scan | parse | codinter | assembly ]"
            fi
        ;;

        # Degug
        -debug)
            echo "-debug"
            echo
            if [ "$2" != "" ]; then
                if [ "$3" != "" ]; then
                    if [ "$3" == "-op" ]; then
                        ./pascaltds 1 1 1 < "./"$2
                    else
                        echo "Error: Unknown flag '"$3"'."  
                        exit 
                    fi
                else
                    ./pascaltds 1 1 0 < "./"$2
                fi
                gcc assemblyCode.s -o assemblyCode
            else
                echo "Error: Empty file parameter"
                exit
            fi
        ;;

        # Show intermediate code.
        -ic)
            echo "-ic"
            echo
            if [ "$2" != "" ]; then
                if [ "$3" != "" ]; then
                    if [ "$3" == "-op" ]; then
                        ./pascaltds 2 1 1 < "./"$2
                    else
                        echo "Error: Unknown flag '"$3"'."  
                        exit 
                    fi
                else
                    ./pascaltds 2 1 0 < "./"$2
                fi
                gcc assemblyCode.s -o assemblyCode
            else
                echo "Error: Empty file parameter"
                 exit
            fi
        ;;

        ## Show assembly code.
        -ac)
            echo "-ac"
            echo
            if [ "$2" != "" ]; then
                if [ "$3" != "" ]; then
                    if [ "$3" == "-op" ]; then
                        ./pascaltds 3 1 1 < "./"$2
                    else
                        echo "Error: Unknown flag '"$3"'."  
                        exit 
                    fi
                else
                    ./pascaltds 3 1 0 < "./"$2
                fi
                gcc assemblyCode.s -o assemblyCode
            else
                echo "Error: Empty file parameter"
                 exit
            fi
        ;;

        *)
            if [ "$2" != "" ]; then
                if [ "$2" == "-op" ]; then
                    ./pascaltds 0 1 1 < "./"$1
                else
                    echo "Error: Unknown flag '"$2"'."  
                    exit 
                fi
            else
                ./pascaltds 0 1 0 < "./"$1
            fi
            gcc assemblyCode.s -o assemblyCode
        ;;
    esac
else
    echo "Error: flag not found"
    exit
fi

echo
echo "---------------------------------- DONE ------------------------------------"
echo

exit
